# Generated by Django 3.2.8 on 2021-10-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_title', models.CharField(max_length=255, verbose_name='Channel title')),
                ('source', models.URLField(verbose_name='Feed source')),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
            },
        ),
        migrations.CreateModel(
            name='SourceForParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_for_parse', models.URLField(verbose_name='Source for parse')),
            ],
            options={
                'verbose_name': 'Source for parse',
                'verbose_name_plural': 'Sources for parse',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('pub_date', models.DateField(verbose_name='Publication date')),
                ('link', models.URLField(verbose_name='Link')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Author')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('more_description', models.TextField(blank=True, null=True, verbose_name='More description')),
                ('comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comments')),
                ('media_objects', models.TextField(blank=True, null=True, verbose_name='Media Object')),
                ('extra_links', models.TextField(blank=True, null=True, verbose_name='Extra_links')),
                ('source_feed', models.TextField(blank=True, null=True, verbose_name='Source')),
                ('channel_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='reader.feed', verbose_name='Channel title')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
